# Generated by Django 2.0.5 on 2018-06-28 19:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('led_at', models.DateTimeField(blank=True, null=True, verbose_name='Время прихода')),
                ('led_parent', models.CharField(blank=True, choices=[('F', 'Отец'), ('M', 'Мать')], max_length=1, null=True, verbose_name='Родитель привел')),
                ('took_at', models.DateTimeField(blank=True, null=True, verbose_name='Время ухода')),
                ('took_parent', models.CharField(blank=True, choices=[('F', 'Отец'), ('M', 'Мать')], max_length=1, null=True, verbose_name='Родитель забрал')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата записи')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.Child')),
            ],
        ),
    ]
