# Generated by Django 2.0.5 on 2018-06-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото')),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата рождения')),
                ('nursery_class', models.CharField(blank=True, max_length=10, verbose_name='Класс')),
                ('is_studying', models.BooleanField(db_index=True, default=False, verbose_name='Учится/нет')),
            ],
        ),
    ]
